title: "Poojitha Chowdary Nethi"
email: "npoojitha19@gmail.com"
description: >-
  Java Full Stack Developer | Portfolio
baseurl: "" # Leave this empty for user.github.io
url: "https://poojitha.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

# Social links
author:
  name   : "Poojitha Chowdary Nethi"
  avatar : "" # You can link to an image later
  bio    : "Java Full Stack Developer | 8+ Years Experience"
  location: "USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:npoojitha19@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/your-link"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/your-github"

# Enable site navigation
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
