# Site settings
title: "Poojitha Chowdary Nethi Portfolio"
email: "npoojitha19@gmail.com"
description: "Java Full Stack Developer with 8 years experience"
baseurl: "" # the subpath of your site, e.g. /portfolio
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Author info
author:
  name: "Poojitha Chowdary Nethi"
  email: "npoojitha19@gmail.com"
  linkedin: "https://linkedin.com/in/yourlinkedin"

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
