title: "Poojitha Chowdary Nethi"
email: "npoojitha19@gmail.com"
description: >-
  Java Full Stack Developer | Portfolio
baseurl: ""
url: "https://poojitha.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

author:
  name   : "Poojitha Chowdary Nethi"
  avatar : "" # Optional: Add image link
  bio    : "Java Full Stack Developer | 8+ Years Experience"
  location: "USA"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:npoojitha19@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/your-link"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/your-github"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
